### ISSUE TITLE
demo运行失败

### ISSUE THREAD

**Issue by Vintage177** [icepoint666/edge-connect-ui#1]
您好，我按照提供的要求配置了环境。但是运行demo会死机，内存消耗会疯狂上升。
我之前运行过Edge connect的源代码，可以运行。
想请问您这是什么原因导致的？

**Comment by icepoint666** [comment]
因为edge-connect输入的图片大小是任意的（分辨率只要是4的倍数就行），你之前可能测试使用的图片分辨率比较小吧，edge-connect的源码之前我在显存4000M的卡上跑，有些图片稍微大一点就会爆内存，不过这个demo把图片压缩在固定512x512大小了，至少我在11G显存的卡上运行是没有任何问题（实际也不需要这么大显存）大概5000/6000 M可能就可以吧（我没有测试过这个）

**Comment by Vintage177** [comment]
> 因为edge-connect输入的图片大小是任意的（分辨率只要是4的倍数就行），你之前可能测试使用的图片分辨率比较小吧，edge-connect的源码之前我在显存4000M的卡上跑，有些图片稍微大一点就会爆内存，不过这个demo把图片压缩在固定512x512大小了，至少我在11G显存的卡上运行是没有任何问题（实际也不需要这么大显存）大概5000/6000 M可能就可以吧（我没有测试过这个）

**Comment by Vintage177** [comment]
您好，感谢您的回复
抱歉是我描述问题不清楚。我遇到的问题是...打不开那个demo的UI界面。一运行就死机。
我的环境是 windows10 anaconda的python3.6。pytorch是1.0.0版本的 pyqt5 opencv什么的也都有。
您方便留一个邮箱给我方便交流吗？
![1](https://user-images.githubusercontent.com/37999924/56742748-e7f05f00-67a7-11e9-99a2-0ad172c41166.png)

**Comment by icepoint666** [comment]
可以的，(1023553676@qq.com) 这个应该是在加载模型的时候爆内存了
